services:
  - type: web
    name: my-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 1 main:app --bind 0.0.0.0:10000

